# Generated by Django 4.2 on 2024-06-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='mensaje_cifrado',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(upload_to='proyectos/'),
        ),
    ]
